### ISSUE TITLE
Generating sequences with given values

### ISSUE THREAD

**Issue by Mec-iS** [liborty/random#2]
Thanks for this library.

I couldn't find an example to generate vectors or matrices containing only 0s and 1s. I see there are lot of examples about how to generate numbers in ranges but no way of generating sequences with given values.

Maybe a method to like `ranvv_given(&self, d:usize, values: Vec<T>)` where `d` is the length of the sequence and `values` can accept a vector so to generate something like:
```rust
ranvv_given(3, vec![0., 1.]);
> [0., 1., 1.]
```
or also
```rust
ranvv_given(5, vec![0., 0.5, 1.]);
> [0., 1., 0.5, 1., 1.]
```

That would be helpful for my tests.

**Comment by liborty** [comment]
I have added to the nightly (github) code an example on how to generate binary numbers.
It is not really worth releasing a new crates.io version, so for now it is only on github.
It is possible with existing code, similarly to 'throwing dice' example, using `ranv_in`.

```rust
    use ran::{Rnum,Rv,set_seeds,secondary::stringv};
    set_seeds(777777_u64); 
    let ru8 = Rnum::newu8();
    // ten random binary numbers
    if let Rv::U8(vecu8) = ru8.ranv_in(10,0.,1.) {
        println!("\nBinary numbers: {}",stringv(&vecu8)) };   
```
