### ISSUE TITLE
error[E0658]: use of unstable library feature 'local_key_cell_methods'

### ISSUE THREAD

**Issue by ChristopherRabotin** [liborty/random#3]
Hi there,

It seems that one of my dependencies uses your library. Since just a few days ago, the build fails in [CI](https://github.com/nyx-space/nyx/actions/runs/6714368833/job/18247490958?pr=244) on several WIP branches (https://github.com/nyx-space/nyx/pull/246, https://github.com/nyx-space/nyx/pull/244) on the latest stable rust.

```
error[E0658]: use of unstable library feature 'local_key_cell_methods'
  --> /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ran-1.1.4/src/generators.rs:25:33
   |
25 | pub fn get_seed() -> u64 { SEED.get() }
   |                                 ^^^
   |
   = note: see issue #92122 <https://github.com/rust-lang/rust/issues/92122> for more information

error[E0658]: use of unstable library feature 'local_key_cell_methods'
  --> /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ran-1.1.4/src/generators.rs:34:10
   |
34 |     SEED.set(seed); 
   |          ^^^
   |
   = note: see issue #92122 <https://github.com/rust-lang/rust/issues/92122> for more information
```

Any idea how I could fix that issue?

Thanks

**Comment by liborty** [comment]
Yes, this is caused by my 'ran' crate now relying on Rust stable 1.73. If you do 'rust update', it should all compile just fine again.
It is probably a good idea to always be on the latest version of stable Rust, anyway.

**Comment by liborty** [comment]
I know that github is always messing around with their nodes and whatnot, so I use a third party Rust toolchain that has never let me down. For your information, here is my .yml file that passes my 'ran' crate tests on github actions with no problems:

```yml
name: test

on: push

jobs:
  build:  
    name: random 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo test --release -- --test-threads=1 --nocapture --color always    
    ```

**Comment by ChristopherRabotin** [comment]
Thanks for your rapid response. I seem to be encountering an issue in the macos builds, and I'm not sure why that's the case.

**Comment by liborty** [comment]
If you can not resolve it, you can always go back to ran v 1.1.2. The functionality is the same, the later versions are just even  slimmer and faster, that is all.

**Comment by ChristopherRabotin** [comment]
Thanks for the tip. I'll dive into the crux of the issue at a later date,
it seems to be related to the python tool chain I use, so I suspect you're
right in that it is out of date. I don't believe I use the ran crate
directly, I think it's a dependency of one of my dependencies.

**Comment by liborty** [comment]
In Rust, semver it is usually a good idea to specify the dependencies only by the first one or at most two digits of the version number, it will then upgrade the minor versions automatically.

**Comment by ChristopherRabotin** [comment]
I'm still regularly hitting this hiccup, even just now: https://github.com/nyx-space/nyx/actions/runs/6952467949/job/18916580429 . _Sometimes_ rerunning the build will fix the issue, but not always. I'm just kind of surprised about it. Do you have any tips on what I could do to avoid this issue?

**Comment by liborty** [comment]
Like I said before, this will be caused by an old version of Rust < 1.73.
I looked at your actions file and it is not even clear from it which version of Rust it might be using.
If there is any way of specifying Rust >= 1.73, that would fix it.
It is almost certainly caused by an old version getting pulled in somewhere, wherever that might be.

**Comment by ChristopherRabotin** [comment]
I was able to specify the rust toolchain in the CI file: https://github.com/nyx-space/nyx/pull/255/files .
